spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/application_user_account
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog.xml

  jpa:
    show-sql: true
    open-in-view: false

server:
  port: 8081

jwt:
  expirationInMinutes: 10
  key: secreteeffffffffffffffffffffffffffffffffffffffffffaf