spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    show-sql: true
    open-in-view: false

jwt:
  key: secreteeffffffffffffffffffffffffffffffffffffffffffaf

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer