spring:
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    show-sql: true
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false

    listener:
      ack-mode: manual_immediate

jwt:
  key: secreteeffffffffffffffffffffffffffffffffffffffffffaf

limitBooksForPerson: 3